sudo: required
branches:
  only:
    - dev
    
language: node_js
node_js:
  - "10.0.0"
  
before_install: 
  -  cd SSK-FrontEnd-v3


before_script:
  - npm install

script:
  - ng build  --prod --base-href /  --env=prod-huma-num
