sudo: required
branches:
  only:
  - dev
language: node_js
node_js:
- 10.0.0
before_install:
- openssl aes-256-cbc -K $encrypted_74c5bbfe5efa_key -iv $encrypted_74c5bbfe5efa_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- cd SSK-FrontEnd-v3
before_script:
- npm install
script:
- ng build  --prod --base-href /  --env=prod-huma-num
