sudo: required

language: node_js
node_js:
  - "10.0.0"

branches:
  only:
    - dev

before_script:
  - cd SSK-FrontEnd-v3  
  - npm install

script:
  - cd SSK-FrontEnd-v3 
  - ng build  --prod --base-href /  --env=prod-huma-num

